<?php

namespace App\Imports;

use App\Models\Contacts;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Hash;

class ContactsImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Contacts([
            'status'                => 1,
            'first_name'            => $row[0],
            'last_name'             => $row[1],
            'title'                 => $row[2],
            'company'               => $row[3],
            'company_name_for_emails' => $row[4],
            'email'                 => $row[5],
            'email_status'          => $row[6],
            'email_confidence'      => $row[7],
            'seniority'             => $row[8],
            'departments'           => $row[9],
            'contact_owner'         => $row[10],
            'first_phone'           => $row[11],
            'work_direct_phone'     => $row[12],
            'home_phone'            => $row[13],
            'mobile_phone'          => $row[14],
            'corporate_phone'       => $row[15],
            'other_phone'           => $row[16],
            'stage'                 => $row[17],
            'lists'                 => $row[18],
            'last_contacted'        => $row[19],
            'account_owner'         => $row[20],
            'employees'             => $row[21],
            'industry'              => $row[22],
            'keywords'              => $row[23],
            'person_linkedin'      => $row[24],
            'website'               => $row[25],
            'company_linkedin_url'  => $row[26],
            'facebook_url'          => $row[27],
            'twitter_url'           => $row[28],
            'city'                  => $row[29],
            'state'                 => $row[30],
            'country'               => $row[31],
            'company_address'       => $row[32],
            'company_city'          => $row[33],
            'company_state'         => $row[34],
            'company_country'       => $row[35],
            'company_phone'         => $row[36],
            'seo_description'       => $row[37],
            'technologies'          => $row[38],
            'annual_revenue'        => $row[39],
            'total_funding'         => $row[40],
            'latest_funding'        => $row[41],
            'latest_funding_amount' => $row[42],
            'last_raised_at'        => '2024-05-08', // $row[43] ?? $row[43]->format('Y-m-d')
            'email_sent'            => $row[44],
            'email_open'            => $row[45],
            'email_bounced'         => $row[46],
            'replied'               => $row[47],
            'demoed'                => $row[48],
            'number_of_retail_locations'  => $row[49],
            'apollo_contact_id'     => $row[50],
            'apollo_account_id'     => $row[51],
            // 'name'                  => $row['First Name'] . ' ' . $row['Last Name'],
            // 'email'                 => $row['Email'],
            // 'title'                 => $row['Title'],
            // 'company'               => $row['Company'],
            // 'email_status'          => $row['Email Status'],
            // 'email_confidence'      => $row['Email Confidence'],
            // 'seniority'             => $row['Seniority'],
            // 'departments'           => $row['Departments'],
            // 'contact_owner'         => $row['Contact Owner'],
            // 'first_phone'           => $row['First Phone'],
            // 'work_direct_phone'     => $row['Work Direct Phone'],
            // 'home_phone'            => $row['Home Phone'],
            // 'mobile_phone'          => $row['Mobile Phone'],
            // 'corporate_phone'       => $row['Corporate Phone'],
            // 'other_phone'           => $row['Other Phone'],
            // 'stage'                 => $row['Stage'],
            // 'lists'                 => $row['Lists'],
            // 'last_contacted'        => $row['Last Contacted'],
            // 'account_owner'         => $row['Account Owner'],
            // 'num_employees'         => $row['# Employees'],
            // 'industry'              => $row['Industry'],
            // 'keywords'              => $row['Keywords'],
            // 'person_linkedin_url'   => $row['Person Linkedin Url'],
            // 'website'               => $row['Website'],
            // 'company_linkedin_url'  => $row['Company Linkedin Url'],
            // 'facebook_url'          => $row['Facebook Url'],
            // 'twitter_url'           => $row['Twitter Url'],
            // 'city'                  => $row['City'],
            // 'state'                 => $row['State'],
            // 'country'               => $row['Country'],
            // 'company_address'       => $row['Company Address'],
            // 'company_city'          => $row['Company City'],
            // 'company_state'         => $row['Company State'],
            // 'company_country'       => $row['Company Country'],
            // 'company_phone'         => $row['Company Phone'],
            // 'seo_description'       => $row['SEO Description'],
            // 'technologies'          => $row['Technologies'],
            // 'annual_revenue'        => $row['Annual Revenue'],
            // 'total_funding'         => $row['Total Funding'],
            // 'latest_funding'        => $row['Latest Funding'],
            // 'latest_funding_amount' => $row['Latest Funding Amount'],
            // 'last_raised_at'        => $row['Last Raised At'],
            // 'email_sent'            => $row['Email Sent'],
            // 'email_open'            => $row['Email Open'],
            // 'email_bounced'         => $row['Email Bounced'],
            // 'replied'               => $row['Replied'],
            // 'demoed'                => $row['Demoed'],
            // 'num_retail_locations'  => $row['Number of Retail Locations'],
            // 'apollo_contact_id'     => $row['Apollo Contact Id'],
            // 'apollo_account_id'     => $row['Apollo Account Id'],
        ]);
    }
}
